### ISSUE TITLE
Only able to draw with in the package

### ISSUE THREAD

**Issue by MeteoBoy4** [WCHAR-NCL/Dot-Matrix#2]
I can only draw successively when the script is in the Dot-Matrix folder, or it will raise errors about 
cannot find the font?

**Comment by wqshen** [comment]
Please tell me the directory structure of Dot-Matrix in your system.
Also, if you refer to our document <[Dot-Matrix/NCL图形加中文.pdf](https://github.com/WCHAR-NCL/Dot-Matrix/blob/master/NCL%E5%9B%BE%E5%BD%A2%E5%8A%A0%E4%B8%AD%E6%96%87.pdf)> ?

**Comment by MeteoBoy4** [comment]
I copied the whole git master branch to $NCARG_ROOT, so it should be the same with the online version.
I used the simplest Xfont drawing with no resource, and it reported could not found './Fontlib/S/balabala
I changed the DotDir in the WCHAR.ncl to the $NCARG_ROOT (originally ./), it worked?

**Comment by wqshen** [comment]
Yeh, you can change the DotDir variable in the WCHAR.ncl. i am sure it will work.
I'll revise the source code and document as soon as possible,
also thank you for your report.

**Comment by MeteoBoy4** [comment]
That's it! Very appreciated for your effort, I think this issue can be closed ~
